# Generated by Django 4.1.6 on 2023-05-13 09:00

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=django_fsm.FSMField(default='new', max_length=50),
        ),
    ]
