# Generated by Django 4.1.6 on 2023-05-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_recommendation_delete_shop_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
